(WIP) Format toRuby
mitre/ts-inspec-objects pull request #8
Opened 2022-12-13 17:26 UTC by em-c-rod

2022-12-16 16:36 UTC, ejaronne commented
Questions: 
Does this preserve the exact original content from the guidance document (STIG, CIS, Vendor)? For example, command-line instructions from the author may have very specific punctuation that needs to be preserved exactly as intended.

Does it also not artificially wrap text (especially check and fix text), which may already have carriage returns and/or linefeeds in the original content?  I know we've struggled over the years to ensure stuff looks decent in Heimdall, csv, cli, CAAT, ckl.

2022-12-16 19:32 UTC, aaronlippold requested changes

2022-12-16 19:32 UTC, aaronlippold commented on src/objects/control.ts
> +            console.error(`${this.id} has a redundant default value. This command will write the "desc" value to the control and will not write the "default" value.`);
This is what is expected. The new standard is to use the .descriptions.... object , the main desc object is there for backwards compatibility.

2022-12-16 19:32 UTC, aaronlippold commented on src/objects/control.ts
> +            console.error(`${this.id} has a redundant default value. This command will write the "desc" value to the control and will not write the "default" value.`);
you can review the profile schema or the ruby inspec-objects as a reference if needed in the future.

2022-12-16 19:32 UTC, aaronlippold commented on test/tests/control.spec.ts
> +    // This check is comparing what the function "toRuby" is outputting with a small sample profile that has been formatted
Please start the TSDoc process here and expand it out at least as a simple lift and shift and start the minimal GitHub Action to generate the TSDocs - <http://tsdocs.org>

2022-12-23 01:43 UTC, aaronlippold approved these changes

2022-12-28 17:43 UTC, merged